name: ML Prediction Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-prediction:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Pull Your ML Docker Image
      run: |
        docker pull guardvision/ml_project:v1.0

    - name: Run Docker ML API
      run: |
        docker run -d -p 8000:8000 --name ml_api guardvision/ml_project:v1.0
        sleep 10  # API'nin açılmasını bekle

    - name: Run Prediction Python Script
      run: |
        python predictor.py

    - name: Upload result.json as artifact
      uses: actions/upload-artifact@v4
      with:
        name: prediction-output
        path: result.json

    - name: Stop container
      run: |
        docker stop ml_api
        docker rm ml_api
